# Generated by Django 4.1.1 on 2022-09-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
